package com.chaincomp.quickmybaits.mapper;

import com.chaincomp.quickmybaits.model.SysUser;
import org.apache.ibatis.annotations.Select;

import java.util.List;

public interface SysUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testuser
     *
     * @mbg.generated
     */
    int insert(SysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testuser
     *
     * @mbg.generated
     */
    int insertSelective(SysUser record);


    @Select("select * from testuser")
    List<SysUser> findAllUsers();
}