package com.chaincomp.quickmybaits.mapper;

import com.chaincomp.quickmybaits.model.SysUser;

public interface SysUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testuser
     *
     * @mbg.generated
     */
    int insert(SysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testuser
     *
     * @mbg.generated
     */
    int insertSelective(SysUser record);
}